version: '3.4'

networks:
  humanhack-dev:
    driver: bridge

services:
  humanhackserver:
    container_name: humanhack-server
    image: ${DOCKER_REGISTRY-}humanhackserver
    build:
      context: .
      dockerfile: HumanHackServer/Dockerfile
    ports:
        - 5000:80
    networks:
        - humanhack-dev
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=humanhack;IntegratedSecurity=true;Pooling=true;

  proxy:
    container_name: reverse-proxy
    image: nginx:mainline
    networks:
        - humanhack-dev
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80  
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres_db
        POSTGRES_USER: postgres
    ports:
        - 5432:5432
    networks:
        - humanhack-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data

  Intelligent_Routing_Customer_api:
    container_name: java-api-server
    image: java-rest-api:latest
    build:
       context: .
       dockerfile: Intelligent_Routing_Customer_api/Dockerfile
    ports:
        - 2020:8080 
    networks:
        - humanhack-dev
    restart: always

volumes:
  postgres-data: